project:
  name: "mushroom_classification_baseline"
  description: "Manual Baseline: Random Forest without odor feature"
  seed: 42

paths:
  raw_data: "data/raw/mushrooms.csv"
  processed_data: "data/processed/"
  output_dir: "outputs/"

mlflow:
  tracking_uri: "file:./mlruns"
  # Змінили назву експерименту, щоб відділити його від майбутніх тестів
  experiment_name: "mushroom_rf_no_odor"

data:
  target_column: "class"
  test_size: 0.2
  stratify: true
  # ВАЖЛИВО: Саме тут ми вказуємо, що цю колонку треба викинути
  drop_columns: ["odor"]

# Нова секція спеціально для Random Forest
model:
  type: "RandomForestClassifier"
  n_estimators: 100
  max_depth: 10
  min_samples_split: 5
  class_weight: "balanced"  # Допомагає, якщо є дисбаланс класів